spring.application.name=products
server.port=8082

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/wp2-project}

wovely.app.jwtSecret=======================Wovely=Spring=Boot=Secret=Key======================
wovely.app.jwtExpirationMs=86400000

inventory.api.url=${INVENTORY_API_URL:http://localhost:8083/api/inventory}
