spring.application.name=wovely
server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/wp2-project

wovely.app.jwtSecret=======================Wovely=Spring=Boot=Secret=Key======================
wovely.app.jwtExpirationMs=86400000
