server.port=8083
spring.data.mongodb.uri=mongodb://localhost:27017/wp2-project
spring.data.mongodb.database=wp2-project

# JWT Configuration
jwt.secret========================Wovely=Spring=Boot=Secret=Key======================
jwt.expiration=86400000

# CORS Configuration
cors.allowed.origins=http://localhost:4200
