server.port=8083
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/wp2-project}

# JWT Configuration
jwt.secret=======================Wovely=Spring=Boot=Secret=Key======================
jwt.expiration=86400000

# CORS Configuration
cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
