server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.csr.html index.html;

    location / {
        try_files $uri $uri/ /index.csr.html;
    }

    # Proxy API requests if needed, but here we expect the browser to talk directly to backends
    # If we wanted to proxy them:
    # location /api/auth {
    #     proxy_pass http://wovely-backend:8081;
    # }
}
