spring.application.name=products
server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/wovely_db

wovely.app.jwtSecret=wovelySecretKeyThatIsAtLeast32BytesLongForHS256Algorithm
wovely.app.jwtExpirationMs=86400000
