spring.application.name=products
server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/wovely_db

wovely.app.jwtSecret=======================Wovely=Spring=Boot=Secret=Key======================
wovely.app.jwtExpirationMs=86400000
